### ISSUE TITLE
是很久没更新的缘故吗？网络连不太上

### ISSUE THREAD

**Issue by lemos1235** [gogoforit/bilibili-voice#1]
![image](https://user-images.githubusercontent.com/23135552/38144644-3c180696-3478-11e8-94c0-ed144cfd4249.png)

**Comment by po1ng** [comment]
-_-||  B站的API规格改了  导致曲目信息没办法解析了 最近太忙了 应该近期没办法更新了  如果有兴趣你可以尝试一下 曲目解析部分的API规则改一下应该就可以了   然后mpv和youtube-dl更新到最新版本
